# Generated by Django 5.0 on 2023-12-24 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(default='non url', verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(default='non url', verbose_name='Image URL')),
                ('name', models.TextField(default='vanilla', verbose_name='Name')),
                ('min_float', models.FloatField(null=True, verbose_name='Minimum Float')),
                ('max_float', models.FloatField(null=True, verbose_name='Maximum Float')),
            ],
            options={
                'verbose_name': 'Skin',
                'verbose_name_plural': 'Skins',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(default='non url', verbose_name='Image URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Pattern',
                'verbose_name_plural': 'Patterns',
            },
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Rarity name')),
            ],
            options={
                'verbose_name': 'Rarity',
                'verbose_name_plural': 'Raritys',
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(default='non url', verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
            },
        ),
        migrations.CreateModel(
            name='RareSkin',
            fields=[
                ('skin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.skin')),
                ('crates', models.ManyToManyField(to='skins.case', verbose_name='Cases')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.skin',),
        ),
        migrations.AddField(
            model_name='skin',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skins.collection'),
        ),
        migrations.AddField(
            model_name='skin',
            name='pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skins.pattern', verbose_name='Pattern'),
        ),
        migrations.AddField(
            model_name='skin',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.rarity', verbose_name='Rarity'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(default='non url', verbose_name='Image URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.category')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
        ),
        migrations.AddField(
            model_name='skin',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.weapon', verbose_name='Weapon'),
        ),
        migrations.CreateModel(
            name='CaseSkin',
            fields=[
                ('skin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.skin')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.case', verbose_name='Case')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.skin',),
        ),
        migrations.CreateModel(
            name='GloveSkin',
            fields=[
                ('rareskin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.rareskin')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.rareskin',),
        ),
        migrations.CreateModel(
            name='KniveSkin',
            fields=[
                ('rareskin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.rareskin')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.rareskin',),
        ),
        migrations.CreateModel(
            name='SouvenirSkin',
            fields=[
                ('skin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.skin')),
                ('crates', models.ManyToManyField(to='skins.souvenir', verbose_name='Soubenir packages')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.skin',),
        ),
    ]
