# Generated by Django 5.0 on 2023-12-19 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(verbose_name='Image URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(verbose_name='Image URL')),
                ('first_sale_date', models.DateField(verbose_name='First Sale Date')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.collection')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
            },
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(verbose_name='Image URL')),
                ('first_sale_date', models.DateField(verbose_name='First Sale Date')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.collection')),
            ],
            options={
                'verbose_name': 'Souvenir',
                'verbose_name_plural': 'Souvenirs',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(verbose_name='Image URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.category')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.URLField(verbose_name='Image URL')),
                ('rarity', models.CharField(max_length=50, verbose_name='Rarity')),
                ('pattern_string', models.CharField(max_length=50, verbose_name='Pattern String')),
                ('min_float', models.FloatField(verbose_name='Minimum Float')),
                ('max_float', models.FloatField(verbose_name='Maximum Float')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.collection')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.weapon')),
            ],
            options={
                'verbose_name': 'Skin',
                'verbose_name_plural': 'Skins',
            },
        ),
        migrations.CreateModel(
            name='CaseSkin',
            fields=[
                ('skin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.skin')),
                ('create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.case')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.skin',),
        ),
        migrations.CreateModel(
            name='SouvenirSkin',
            fields=[
                ('skin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.skin')),
                ('create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.souvenir')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.skin',),
        ),
    ]
