# Generated by Django 5.0 on 2023-12-21 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseskin',
            old_name='create',
            new_name='crate',
        ),
        migrations.RenameField(
            model_name='souvenirskin',
            old_name='create',
            new_name='crate',
        ),
    ]
