# Generated by Django 5.0 on 2023-12-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_rename_create_caseskin_crate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RareSkin',
            fields=[
                ('skin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.skin')),
                ('crate', models.ManyToManyField(to='skins.case', verbose_name='Cases')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.skin',),
        ),
        migrations.AlterField(
            model_name='skin',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skins.collection'),
        ),
        migrations.CreateModel(
            name='GloveSkin',
            fields=[
                ('rareskin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.rareskin')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.rareskin',),
        ),
        migrations.CreateModel(
            name='KniveSkin',
            fields=[
                ('rareskin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='skins.rareskin')),
            ],
            options={
                'abstract': False,
            },
            bases=('skins.rareskin',),
        ),
    ]
